import Head from 'next/head'
import Image from 'next/image'
import Navbar from 'components/navbar'
import MainText from '@/components/maintext'
import Card from '@/components/card'
import Products from "@/components/products"

export default function Home() {
  return (
    <>
      <Head>
        <title>Topelec</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className = "main flex flex-col">
        <Image width = {1000} height = {1000} alt = "industrial" src = "/assets/test.png" className = "absolute z-1 main-image w-full h-full object-cover"/>
        <MainText />
        <div className = "relative flex-grow-1 z-10 items-center flex justify-center text-center mb-4">
          <Image width = {70} height = {70} alt = "scroll-down" src = "/assets/arrow.png" className = "arrow-down"/>
        </div>
        <Navbar />
      </div>

      <div className = "values flex flex-col items-center justify-center">
        <p className = "font-hb text-5xl mt-16">Our Values</p>
        <div className = "flex flex-row justify-between w-full px-32 mt-2" id = "products">
          <Card id = "trend" name = "Value 1" text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. amet, consectetur adipiscing elit. " />
          <Card id = "sprout" name = "Value 2" text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. amet, consectetur adipiscing elit."/>
          <Card id = "industry-40" name = "Value 3" text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. amet, consectetur adipiscing elit."/>
        </div>
      </div>

      <Products />


    </>
  )
}
